# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# fastlane set_version version_number:2.0.0
lane :set_version  do |options|
  new_version_nr = increment_version_number(version_number: options[:version_number])
end

lane :bump_build do
  build_nr = increment_build_number
end

# fastlane set_build build_number:123"
lane :set_build  do |options|
  increment_build_number(build_number: options[:build_number])
end
